### PR TITLE
%property overhaul

### LINKED ISSUE #41: Defining %property while override setter
I'm gonna ditch the standard issue template because I don't see it fitting.

Defining a property like 

```
%subclass NextUpMediaHeaderView : MediaControlsHeaderView
%property (nonatomic, retain) UIColor *textColor;

...

%end
```

is fine. However, I'd like to override the setter:

```
%subclass NextUpMediaHeaderView : MediaControlsHeaderView
%property (nonatomic, retain) UIColor *textColor;


- (void)setTextColor:(UIColor *)color {
    %orig;

    // some extra stuff being made here
}

...

%end
```

and this is not possible as it complains about it being redefined.

```
NextUp.xm:417:17: error: redefinition of
      '_logos_method$CustomViews$NextUpMediaHeaderView$setTextColor$'
    static void _logos_method$CustomViews$NextUpMediaHeaderView$setTextColor$(...
                ^
NextUp.xm:367:377: note: previous definition is here
  ...}__attribute__((used)) static void _logos_method$CustomViews$NextUpMediaHeader...
```

I know we need to define methods to set and get associated objects when defining a new property, but could it perhaps be tweaked to call a custom setter afterwards if such exists or something?

I'm aware of the obvious solution of defining a method like `updateTextColor:` which sets the property and does the extra work. It's just isn't that good looking code, and it would also be confusing for others using already a defined class where this approach is used.

### PR DESCRIPTION
**Pull request by NSExceptional**
## Motivation

`%properties` have a few problems currently:

- They don't generate `objc_property` metadata by calling into `class_addProperty`
- You cannot make a `readonly` property
- You cannot opt-out of backing storage
- You cannot override the synthesized methods and then call back into them with `%orig`

This PR resolves all of these issues.

### `readonly` Properties

Now, marking a %property as `readonly` will not synthesize a getter and setter.

#### Rationale

Clang will not synthesize a backing ivar when you implement both the getter and setter of a property (or when you implement the getter of a readonly property) because it reasonably assumes you don't _need_ backing storage

Likewise, if you mark a %property as `readonly` Logos will assume that you plan to add a computed property which doesn't need backing storage. This makes sense since Logos's generated getters use associated objects, and you would need to provide some kind of setter-logic if you did need backing storage.

### Overriding Properties

Prior to this, if you were to `%hook` a method and try to add a `%property` with the same name, the generated logos symbols would collide. This resolves that collision by renaming the symbol generated by Logos. `%property` method symbols now look like `…$myProperty$getter` or `…$myProperty$setter` instead of `…$myProperty` and `…$setMyProperty`

### Order of Class Initialization

Before, methods (hooks) were initialized before properties. This means that property methods didn't exist yet to be hooked. Swapping the order fixes this.

---

This closes #41

### CODE REVIEW

File: bin/lib/Logos/Generator/Base/Property.pm [hunk 1]
```diff
@@ -5,19 +5,33 @@ use Logos::Util;
 sub getterName {
 	my $self = shift;
 	my $property = shift;
-	return Logos::sigil("method", $property->group->name, $property->class->name, $property->getter);
+	return Logos::sigil("method", $property->group->name, $property->class->name, $property->getter, "getter");
```
Comment (uroboro) [inline bin/lib/Logos/Generator/Base/Property.pm:8]: Why this change? The difference for these functions already happens in https://github.com/theos/logos/blob/master/bin/logos.pl#L678-L691

File: bin/lib/Logos/Class.pm [hunk 2]
```diff
@@ -25,12 +25,15 @@ sub new {
 ##################### #
 # Setters and Getters #
 # #####################
+
+# Such as 'UIView'
```
Comment (uroboro) [inline bin/lib/Logos/Class.pm:29]: Shouldn't this be something like `'customView' from 'UIView * customView'`?

File: bin/lib/Logos/Generator/Base/Class.pm [hunk 3]
```diff
@@ -49,10 +49,10 @@ sub initializers {
 	my $self = shift;
 	my $class = shift;
 	my $return = "";
-	for(@{$class->methods}) {
+	for(@{$class->properties}) {
```
Comment (uroboro) [inline bin/lib/Logos/Generator/Base/Class.pm:52]: Why this swap?

File: bin/lib/Logos/Generator/Base/Property.pm [hunk 4]
```diff
@@ -5,19 +5,33 @@ use Logos::Util;
...
+# addAttribute(attributeList, attributeCount, attributeName, attributeValue)
+#
+# attributeName is one of the property attribute characters, it will be "stringified" for you
+# attribute value must be a variable or something else; it will NOT be "stringified" for you; omit it to use ""
+sub addAttribute {
+	my $self = shift;
+	my $attrList = shift;
+	my $counter = shift;
+	my $name = shift;
+	my $value = shift // "\"\"";
```
Comment (uroboro) [inline bin/lib/Logos/Generator/Base/Property.pm:26]: Can you use `'""'` to reduce escapes?

File: bin/lib/Logos/Generator/Base/Property.pm [hunk 5]
```diff
@@ -5,19 +5,33 @@ use Logos::Util;
...
+	return " $attrList [$counter++] = (objc_property_attribute_t) { \"$name\", $value };";
```
Comment (uroboro) [inline bin/lib/Logos/Generator/Base/Property.pm:27]: Remove the space in `$attrList [$counter++]`

File: bin/lib/Logos/Generator/Base/Property.pm [hunk 6]
```diff
@@ -27,47 +41,89 @@ sub definition {
...
+			$setter_func .= "{ NSValue * value = [NSValue valueWithBytes:&rawValue objCType:\@encode($propertyType)]; objc_setAssociatedObject(self, (void *)$propertyGetterName, value, OBJC_ASSOCIATION_RETAIN_NONATOMIC); }";
+		} else {
+			$setter_func .= "{ objc_setAssociatedObject(self, (void *)$propertyGetterName, rawValue, $propertyAssociationPolicy); }";
+		}
+
+		return "$getter_func;\n$setter_func";
 	}
 
-	return "$getter_func; $setter_func";
+	return "";
```
Comment (uroboro) [inline bin/lib/Logos/Generator/Base/Property.pm:66]: Could we have the `else` clause here and explain why we don't add getters/setters for readonly properties? (the it'd contain the `return "";`)
Am I right thinking that the idea is to let the user create a getter method, as opposed to public readonly in `@interface` and private readwrite in `@implementation` for the normal iOS development?

File: bin/lib/Logos/Generator/Base/Property.pm [hunk 7]
```diff
@@ -27,47 +41,89 @@ sub definition {
...
+	my $name = $property->name;
 	my $propertyType = $property->type;
 	my $propertyGetter = $property->getter;
 	my $propertyGetterName = $self->getterName($property);
 	my $propertySetter = $property->setter;
 	my $propertySetterName = $self->setterName($property);
 
-	my $build = "{ char _typeEncoding[1024];";
+	$propertyType =~ /([^ \*]+).+/;
+	my $propertyClassName = $1;
```
Comment (uroboro) [inline bin/lib/Logos/Generator/Base/Property.pm:87]: Will this work if I declare a property with generics (`NSArray<NSString *> *`)? Does that actually work currently 🤔?

File: bin/lib/Logos/Generator/Base/Property.pm [hunk 8]
```diff
@@ -27,47 +41,89 @@ sub definition {
...
+	
+	my $build = "{ objc_property_attribute_t _attributes[16]; unsigned int attrc = 0;";
+
+	# Property attributes
+	if ($retain) {
+		# Type encoding of objet properties should be `@"ClassName"`
+		$build .= $self->addAttribute("_attributes", "attrc", "T", "\"@\\\"$propertyClassName\\\"\"");
```
Comment (uroboro) [inline bin/lib/Logos/Generator/Base/Property.pm:94]: Same comment as before regarding escapes.

File: bin/lib/Logos/Generator/Base/Property.pm [hunk 9]
```diff
@@ -27,47 +41,89 @@ sub definition {
...
+		$build .= $self->addAttribute("_attributes", "attrc", "&"); #, "\"\"");
```
Comment (uroboro) [inline bin/lib/Logos/Generator/Base/Property.pm:95]: Remove unused comments.

File: bin/logos.pl [hunk 10]
```diff
@@ -643,6 +645,8 @@ package main;
 			$property->class($currentClass);
 			$property->type($type);
 			$property->name($name);
+			$property->readonly($readonly);
```
Comment (uroboro) [inline bin/logos.pl:648]: Can't place my comment in the area of L630-640 to request adding checks for cases like having both `readonly` and `retain` on the attribute list, which seems contradictory.

File: bin/lib/Logos/Generator/Base/Property.pm (hunk 1 above)
Comment (NSExceptional) [reply bin/lib/Logos/Generator/Base/Property.pm:8]: This disambiguates it from any methods you might be trying to hook

File: bin/lib/Logos/Class.pm (hunk 2 above)
Comment (NSExceptional) [reply bin/lib/Logos/Class.pm:29]: I don't think so but I'll double check

File: bin/lib/Logos/Generator/Base/Class.pm (hunk 3 above)
Comment (NSExceptional) [reply bin/lib/Logos/Generator/Base/Class.pm:52]: Look at the message in my last commit

File: bin/lib/Logos/Generator/Base/Property.pm (hunk 5 above)
Comment (NSExceptional) [reply bin/lib/Logos/Generator/Base/Property.pm:27]: Without the space it thinks `attrList` is a global variable. Can you clone this and see if you can figure out how to work around it?

File: bin/lib/Logos/Generator/Base/Property.pm (hunk 7 above)
Comment (NSExceptional) [reply bin/lib/Logos/Generator/Base/Property.pm:87]: Oop, I didn't test that. It works for `T *` currently.

**Comment by NSExceptional** [comment]
Thanks! I'll address these in a little while with changes. I left some comments too.

File: bin/lib/Logos/Generator/Base/Property.pm (hunk 1 above)
Comment (uroboro) [reply bin/lib/Logos/Generator/Base/Property.pm:8]: > if you were to %hook a method and try to add a %property with the same name, the generated logos symbols would collide

I'm concerned about people hooking a method and adding a property with the same name (same selector), which I think isn't right.

File: bin/lib/Logos/Generator/Base/Class.pm (hunk 3 above)
Comment (uroboro) [reply bin/lib/Logos/Generator/Base/Class.pm:52]: > Initializing %properties before method hooks allows properties to be hooked by methods.

Why would you do that?

File: bin/lib/Logos/Generator/Base/Property.pm (hunk 5 above)
Comment (uroboro) [reply bin/lib/Logos/Generator/Base/Property.pm:27]: Do you mean that Perl thinks its a variable?
You can do this then:
`return " ".$attrList."[$counter++] = ...`

File: bin/lib/Logos/Generator/Base/Property.pm (hunk 1 above)
Comment (NSExceptional) [reply bin/lib/Logos/Generator/Base/Property.pm:8]: Why isn't it right? It's very common to want to add additional behavior to a getter or setter. There's even an open issue about this, I think it's #41?

File: bin/lib/Logos/Generator/Base/Property.pm (hunk 5 above)
Comment (NSExceptional) [reply bin/lib/Logos/Generator/Base/Property.pm:27]: Yeah. Thanks!

File: bin/lib/Logos/Class.pm (hunk 2 above)
Comment (NSExceptional) [reply bin/lib/Logos/Class.pm:29]: I'm correct, it's the name of a type, such as `UIView` from `%hook UIView`. [For example](https://github.com/theos/logos/blob/master/bin/logos.pl#L249-L263)

File: bin/lib/Logos/Generator/Base/Class.pm (hunk 3 above)
Comment (NSExceptional) [reply bin/lib/Logos/Generator/Base/Class.pm:52]: #41

File: bin/lib/Logos/Generator/Base/Property.pm (hunk 6 above)
Comment (NSExceptional) [reply bin/lib/Logos/Generator/Base/Property.pm:66]: > Am I right thinking that the idea is to let the user create a getter method

Yes

File: bin/lib/Logos/Generator/Base/Property.pm (hunk 7 above)
Comment (NSExceptional) [reply bin/lib/Logos/Generator/Base/Property.pm:87]: Fixed by adding `<` to the `[^…]` part. This regex assumes the property type is captured property already, so it just matches the first blob that doesn't contain a character that can't be part of a valid identifier, like ` ` or `*` or `<`

`^([^ \*<]+).+`

File: bin/logos.pl (hunk 10 above)
Comment (NSExceptional) [reply bin/logos.pl:648]: Added this:

```perl
if($readonly) {
    if($retain || $copy || $assign) {
        fileError($lineno, "property attribute 'readonly' cannot be used with memory management attributes (assign, retain, copy).");
    }
}
```

File: bin/lib/Logos/Generator/Base/Property.pm (hunk 8 above)
Comment (NSExceptional) [reply bin/lib/Logos/Generator/Base/Property.pm:94]:
```perl
'"@\\"'.$propertyClassName.'\\""'
```

**Comment by NSExceptional** [comment]
Changes applied!

File: bin/lib/Logos/Generator/Base/Class.pm (hunk 3 above)
Comment (uroboro) [reply bin/lib/Logos/Generator/Base/Class.pm:52]: It'd be more appropriate to not generate the property methods if the class already has them, no?

Comment (uroboro) [reply bin/lib/Logos/Generator/Base/Class.pm:52]: I now see that hooking the generated methods causes less work to be done: `%orig` would call the generated implementation of the g/setter with no special handling for the method and would not require adding `%new` before it. Let's do it this way.

File: bin/lib/Logos/Generator/Base/Property.pm (hunk 1 above)
Comment (uroboro) [reply bin/lib/Logos/Generator/Base/Property.pm:8]: Undo your additions and replace the first argument `"method"` for `"property"` and we're good.

File: bin/lib/Logos/Class.pm (hunk 2 above)
Comment (uroboro) [reply bin/lib/Logos/Class.pm:29]: Oh right, I didn't notice I was looking at Class.pm

File: bin/lib/Logos/Generator/Base/Property.pm (hunk 1 above)
Comment (NSExceptional) [reply bin/lib/Logos/Generator/Base/Property.pm]: Wow, that is… a much better idea. Dunno why I didn't think to do that instead, lol. Done.
